import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import { UserProvider } from "@/app/context/user";
import { ThemeProvider } from "../components/theme-provider";
import { TaskProvider } from "@/app/context/task";
import { CompanyProvider } from "@/app/(routes)/dashboard/(routes)/companies/context/company";

const poppins = Poppins({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <UserProvider>
            <TaskProvider>
              <CompanyProvider>{children}</CompanyProvider>
            </TaskProvider>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
